backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: public/images
public_folder: /images
logo_url: https://ayni.ch/logo-ayni.svg
collections:
  - label: "Aktuelles" 
    name: "posts"
    folder: "content/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "publishedAt", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown"}
  - label: "Angebot" 
    name: "angebote"
    folder: "content/angebote"
    create: true
    delete: false    
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Subtitle", name: "subtitle", widget: "string"}
      - { label: "SEO Title", name: "seoTitle", widget: "string"}
      - { label: "SEO Description", name: "seoDescription", widget: "string"}
      - { label: "SEO Keywords", name: "seoKeywords", widget: "string"}
      - { label: "Publish Date", name: "publishedAt", widget: "datetime" }
      - { label: "Block 1", name: "block1", widget: "markdown"}
      - { label: "Box Headline", name: "boxHeadline", widget: "string"}
      - { label: "Box Content", name: "boxContent", widget: "markdown"}
      - { label: "Block 2", name: "block2", widget: "markdown"}
  - label: "Informationen" 
    name: "informations"
    folder: "content/informations"
    create: true
    delete: false    
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Subtitle", name: "subtitle", widget: "string"}
      - { label: "SEO Title", name: "seoTitle", widget: "string"}
      - { label: "SEO Description", name: "seoDescription", widget: "string"}
      - { label: "SEO Keywords", name: "seoKeywords", widget: "string"}
      - { label: "Publish Date", name: "publishedAt", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown"}
  - label: "Allgemeines"
    name: "pages"
    create: true
    delete: false    
    files:
      - label: "Testimonials"
        name: "testimonials"
        file: "content/allgemein/testimonials.md"
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Subtitle", name: "subtitle", widget: "string"}
          - { label: "SEO Title", name: "seoTitle", widget: "string"}
          - { label: "SEO Description", name: "seoDescription", widget: "string"}
          - { label: "SEO Keywords", name: "seoKeywords", widget: "string"}
          - label: Testimonial
            name: testimonial
            widget: list
            fields:
              - {label: Titel, name: title, widget: string}
              - {label: Beschreibung, name: description, widget: markdown}
      
  