backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: public/images
public_folder: /images
logo_url: https://ayni.ch/logo-ayni.svg
collections:
  - label: "Aktuelles" 
    name: "posts"
    folder: "content/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "publishedAt", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown"}
  - label: "Informationen" 
    name: "informations"
    folder: "content/informations"
    create: true
    delete: false    
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Subtitle", name: "subtitle", widget: "string"}
      - { label: "SEO Title", name: "seoTitle", widget: "string"}
      - { label: "SEO Description", name: "seoDescription", widget: "string"}
      - { label: "SEO Keywords", name: "seoKeywords", widget: "string"}
      - { label: "Publish Date", name: "publishedAt", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown"}